name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Fixes"
    labels: ["fix", "bug"]
  - title: "📚 Docs"
    labels: ["docs"]
  - title: "⚙️ CI/CD"
    labels: ["ci", "ci-cd"]
  - title: "🧹 Quality"
    labels: ["quality", "refactor", "style"]
  - title: "⚡ Performance"
    labels: ["performance"]
  - title: "🧪 Tests"
    labels: ["tests", "test"]
  - title: "🔒 Security"
    labels: ["security"]
exclude-labels:
  - "skip-changelog"
template: |
  ## What's Changed

  $CHANGES

  ## Contributors
  $CONTRIBUTORS
