me: CI

on:
  push:
    branches: [ main ]
  pull:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build clang clang-tidy

    - name: Configure CMake

      run: cmake -S . -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DBUILD_EXAMPLES=OFF -DBUILD_DOCS=OFF

    - name: Build
      run: cmake --build build -j

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

    - name: Run clang-tidy
      run: clang-tidy -p build $(git ls-files '*.cpp' '*.h') --warnings-as-errors='*'
